### ISSUE TITLE
Geometric mean or median of flow data?

### ISSUE THREAD

**Issue by seananderson** [kchezik/River-Network-Flow-Trends#1]
I'm wondering if a geometric mean or a median would be a better representation of the general tendency of the monthly river flow data? The flow data look quite log-normally distributed:

![flow-distribution](https://cloud.githubusercontent.com/assets/19349/8444032/443ffdf0-1f41-11e5-8040-4e7b75f10cc7.png)

**Comment by kchezik** [comment]
I agree that either would be better than the arithmetic mean. That said I don't know the pros and cons of the geometric mean vs. the median. This would be a super quick fix in the code though so I'm open to either.

**Comment by seananderson** [comment]
It depends on what we're trying to do. These data are positive and continuous. Later we treat them as such as model them on a log scale. That's one reason for going with a geometric mean here. If the data are perfectly log-normal then the geometric mean and median should be identical or nearly identical. The median will be robust to deviations from that distribution. Since the other values are basically quantile values (at 0% and 100%) and are definitely affected by outliers (that's the point), maybe we should use a median? Median is probably a bit more intuitive to think about than geometric mean.

**Comment by kchezik** [comment]
Okay, lets go with the median value. I'll make the update in the code.
