### ISSUE TITLE
Interpolation of flow data for day-of-year analysis

### ISSUE THREAD

**Issue by seananderson** [kchezik/River-Network-Flow-Trends#2]
I feel bad suggesting any change with the interpolation because you obviously put a lot of time into the MARSS model. I do wonder whether, for the purposes of this project, it's best if you go with something much simpler (there will always be another opportunity to use that MARSS knowledge in a future project). There is very little data missing. My worry is that the amount of explanation that will be required to describe and justify the multivariate state space model (and any uncertainty that may create in the eyes of a reader/reviewer) may not be worth it. And my guess is that it really doesn't matter how we interpolate these given they are such a small percentage of the data.

The following code:

```R
par(mfrow = c(3, 3), mar = c(3, 3, 1, 1), cex = 0.5)
plyr::l_ply(Sites, function(i) {
  plot(i)
  points(seq_along(i)[is.na(i)], rep(median(i, na.rm = TRUE), length(is.na(i)))[is.na(i)], 
    col = "red", pch = 20, cex = 2)
})
```

Creates this plot:
![interp](https://cloud.githubusercontent.com/assets/19349/8444370/aafc474e-1f44-11e5-8be5-d55b24cce7cd.png)

There's never less than 6 days of NAs in a row and generally far fewer than that.

```
> Missing
   Station.ID Year Month Days.Missing
1     08ME003 1972   Feb            3
2     08ME003 1972   Jan            5
3     08MG013 1980   Dec            3
4     08MH001 1984   Jan            1
5     08MH001 1989   Nov            2
6     08MH001 1990   Nov            4
7     08MH006 1989   Nov            1
8     08MH056 1989   Nov            2
9     08MH056 1990   Nov            1
10    08MH076 1986   Feb            1
```

What about something like a linear interpolation on a log-scale? Another option would be something like the median value including 10 days before and after the NA string. Even the crazy-naive option of taking the median of the surrounding 2 years looks decent in most cases in that plot (not that I'd suggest that).

**Comment by seananderson** [comment]
PS, I'm happy to implement whatever you decide, if anything. I don't want to create more work for you. Should be quick. I've made a few small commits today swapping in dplyr for some plyr chunks to make huge speed improvements. I checked the output with `identical()` on a subset of the data to make sure I was doing the same thing as the original code.

**Comment by kchezik** [comment]
I'm sure you're right about a simpler model being easier to explain and would probably give us the same answer. I went with the MARSS model largely because I wasn't sure where the missing values fell exactly. There were a lot of 'if's in my mind such as, if the missing value was near the peak flow and the river only had a few days of peak flow during the year, it would have a hugely disproportionate affect on the DOY analysis than a missing day during low flow. Thus it is important we get a fairly realistic estimate of these days. For instance, the right red dot on your middle plot is crazy low and would have a big impact on what day we decide is the day at which we reach half annual flow.

I have thought maybe a simple linear interpolation between a few days before and few days after would be a good alternative to the MARSS model but frequently the days that are missing are in a row which makes this analysis much more difficult and increases the doubt in my mind that we are estimating the values properly. A good example of this is the 08ME003 site for Feb and Jan of 1972. If my memory serves me correct these missing values are 7 straight. The only reason they made the cut for the analysis is that they're in separate months.

Alternatively we could revisit the raw data and ask, how many more sites/years could we include if we allow for more missing data and then use the MARSS model to fill in the gaps. The cut offs I've used for this analysis are arbitrary. I'm simply trying to maximize the number of sites and years without putting the analysis in question for to many interpolated or missing days.

Thoughts?

**Comment by seananderson** [comment]
Hmm. I wonder if we're going to use a threshold for number of continuous missing days then we should do that continuously, not within months. Still, I could see 7 (a week) being a decent arbitrary cutoff, which would get us back to the same place. I thought I counted 6 NAs in a row for 1972, but I may be wrong.

A method that would be in the middle of complexity and jive with the second half of the analysis would be to fit a GAM. Maybe to the same window of data you used and with a smoother for day of year and possibly month plus a factor level for year.

How about I try the simplest: a linear interpolation on a log scale and we look at the plots of the result. If they look reasonable then we stop there, if not then we continue thinking about it. My plots above are justing of the overall median, which wasn't meant to be an interpolation — just an arbitrary place to put a red dot that I knew would be within the axis limits.

**Comment by seananderson** [comment]
Well, I just dug through the code. I was first had grand ambitions to make cull decisions in continuous time instead of grouping by month and year, but then after much confusion I realized you were dropping whole years for some sites based on data missing by month. I guess that's fine and I guess it's best to stick with the same culls for the day-of-year data.

So...

I tried two 'simple' interpolations. One was a loess smoother and the other was a linear interpolation (to the logged data). I think the linear interpolation works pretty well. See the plots here:
<https://dl.dropboxusercontent.com/u/254940/interpolation-checks-approx.pdf>

This uses the `approx()` function in R. E.g.

```R
pdf("interpolation-checks-approx.pdf", width = 14, height = 5)
plyr::l_ply(Sites, function(i) {
	ind <- seq_along(i)
	d <- data.frame(flow = i, ind = ind)
	d$approx <- approx(d$ind[!is.na(d$flow)], y = log(d$flow[!is.na(d$flow)]), 
		xout = d$ind)$y %>% exp()
  plot(d$ind, d$flow, type = "o", pch = 20, cex = 0.6)
  lines(d$ind, d$approx, col = "blue")
  pred_nas <- d[which(is.na(d$flow)), c("ind", "approx")]
  points(pred_nas$ind, pred_nas$approx, col = "red", cex = 1, pch = 20)
})
dev.off()
```

**Comment by kchezik** [comment]
Yeah, I buy those approximations. I guess the linear model works and I'm sure would be simpler to explain. I still need to figure out what your code is doing.

**Comment by seananderson** [comment]
I can simplify the code and embed it into your current MARSS loop. But feel
free to step through that little testing loop and play with the approx
function.

**Comment by seananderson** [comment]
OK, I incorporated the linear interpolation code: https://github.com/kchezik/River-Network-Flow-Trends/commit/0b2f6a20597e437ca9c1f65d56d4637dceb8031b

I think we could greatly simplify that by just joining in the missing data as NAs and then interpolating on the whole dataset at once, but this works and it's done, so I saw we move on.

Regarding the cumulative sum of river flow, I can't quite follow all the logic and it's taking a very very long time to run. What all do you need out of it?

Would something like this work? I could also return the various other info (month etc.) if needed.

```R
accum_flow <- Data.Preds %>%
	group_by(Station.ID, Year) %>%
	mutate(half_total_flow = sum(Flow.Data) / 2) %>%
	summarise(DOY2 = max(DOY[cumsum(Flow.Data) < half_total_flow]))
```

```
accum_flow
Source: local data frame [2,156 x 3]
Groups: Station.ID

   Station.ID Year DOY2
1     08JB002 1970  171
2     08JB002 1971  190
3     08JB002 1972  177
4     08JB002 1973  175
5     08JB002 1974  174
6     08JB002 1975  196
7     08JB002 1976  177
8     08JB002 1977  155
9     08JB002 1978  179
10    08JB002 1979  167
..        ...  ...  ...
```

**Comment by seananderson** [comment]
See if this makes sense: https://github.com/kchezik/River-Network-Flow-Trends/commit/9ebc66a9282f8a3bba36592ecd31c6e05bffa997

**Comment by kchezik** [comment]
Your rewrite is how I imagined the code to work but didn't know several of the functions you used existed nor did I know some of them functioned in the way you used them. It gets us to the same point but I assume your methods is almost instantaneous. Thanks!
