### ISSUE TITLE
Figure showing all month-year GAM trends

### ISSUE THREAD

**Issue by seananderson** [kchezik/River-Network-Flow-Trends#3]
I was thinking of a figure that shows the full GAM models that are then summarized into early and late values. This is probably supplemental, but you could also pick out a few representative panels for the main text.

Instead of the image plots or perspective plots, you could have lines with a different coloured line for each month and a different panel for each river ID. This might help people's intuition about what's going on in the models. I can have a go at this quickly. Should be the same type of data we made the image plots with.

**Comment by kchezik** [comment]
I'm curious to see what you are thinking. I'm imagining two panels side by side with their GAM smoothers coloured by month. This two panel image is then repeated by site vertically into a (2 x n) complete figure? Would the Sites be organized by watershed area? Keeping the axis across sites the same?

**Comment by seananderson** [comment]
What are the two panels side by side?

**Comment by kchezik** [comment]
early and late

**Comment by seananderson** [comment]
Ah, I was just thinking of showing each one continuously (one panel per
river) but maybe with a vertical line at the early/late break. Then they
could be `facet_wrap`ed and ordered by area.

**Comment by kchezik** [comment]
Of course, that's a bit more simple and elegant.

**Comment by kchezik** [comment]
maybe do a shade of colour pallet for early and late so early July is red and late July is more red.

**Comment by seananderson** [comment]
Isn't early/late based on years not months? I was thinking of the circular
rainbow colour scheme for the months. Warm months in warm colours and cool
months in cool colours.

**Comment by kchezik** [comment]
I guess I was thinking that years are imbedded in month so while each month might be some colour of the rainbow, as that months flow regimes change, the colour of that month becomes darker or lighter based on the degree of change. Make sense?
