### ISSUE TITLE
Day-of-year model

### ISSUE THREAD

**Issue by seananderson** [kchezik/River-Network-Flow-Trends#4]
So, technically, the day-of-year response is probably beta-distributed since it's really a positive value between 1 and 365. i.e, it can be thought of as a fraction of a complete year.
 
That's simple to do in R. On the other hand, the distributions look fairly normal I think because they tend to be in the middle of the year and the beta can look just like the normal when it's not too close to 0 or 1. Plots:

![doy-hist](https://cloud.githubusercontent.com/assets/19349/8466784/59db0eb4-200b-11e5-9be8-5c63fc0e46cc.png)
![doy](https://cloud.githubusercontent.com/assets/19349/8466786/5e5016ec-200b-11e5-8b4a-61a956e6b45d.png)

Just throwing this out there:

- one possibility is to leave it exactly as is
- another possibility is to swap beta regression for linear regression
- another possibility is to swap a beta GAM for the linear regression; the relationships look pretty linear to me, but this has the advantage of matching the rest of the analysis; we'd then look at the ratio of recent to early predicted day-of-year at half total flow

**Comment by kchezik** [comment]
There are a couple sites that span the gamut between zero and 1 but most are at 0.5. I know these are the small watershed sites that are incredibly variable. Would there be an effect on these sites if we used beta? Should we use a beta distribution because of these couple sites?

**Comment by kchezik** [comment]
I'm for a linear model. Simple to explain and easy to understand for most folk.
