### ISSUE TITLE
Function Error Fix - "False Convergence (8)"

### ISSUE THREAD

**Issue by kchezik** [kchezik/River-Network-Flow-Trends#7]
Hey Sean, 

I've built the function for the NULL-Model testing but it has not yet run successfully in full because I keep running into a convergence issue with the gls model on line 38.

At first I thought I'll just have the tryCatch function make unsuccessful models NA and then run more iterations than is necessary and sample from those such that we have 1000 models each time. There are a couple problems with this method. Firstly, this means a much longer run time which may not be necessary for many Month-Variable (e.g., Jan-Median, May-Max,....etc.) combinations. Secondly, and most importantly, after the tryCatch function makes the model NA, all the code following the model only works if the model is a data.frame but in this case is a vector (e.g. Model = NA so Model$slope = error). I worked around this by saying if the model is NA then don't do the other stuff but I've had difficulty determining if that is working.

I was thinking there has to be a more elegant way of doing this. Ideally I'd want the full iteration to run again if the gls model fails but can't figure out a way to tell plyr to do this. 

My final effort was to us the tryCatch function to run a different model that included a correlation structure when the first model failed. This seemed to work in most cases but when I tried to run the entire thing last night I came up empty this morning.

Anyways, all of this is to say I'm wondering if you have any ideas on how to deal with this error?

Thanks!

~Kyle

**Comment by seananderson** [comment]
`while() { }`

Wrap the data simulation and model fitting in a while loop and once that condition is met (a model converges) continue on. The caveat is that if this is happening a lot, then we may end up with a biased sample of simulated data.

Have you also played with just increasing the control arguments for gls (more iterations, etc.) to make convergence more likely?

What kind of percentage are we talking about for non-convergence?

**Comment by seananderson** [comment]
An alternative is to substitute in the Stan model. Although we can probably fix the convergence issue that way, the whole thing is almost guaranteed to be slower.

**Comment by kchezik** [comment]
I'd say we are getting maybe 10 non-convergences out of 500 but it depends on the variable and the month.

**Comment by seananderson** [comment]
Can you pull out a couple examples of data that fail? Maybe put a `saveRDS()` in the `tryCatch()` (or do it however you want)

**Comment by seananderson** [comment]
10 out of 500 isn't that bad... with the while loop, it would be good to record the total attempts so we can report that

**Comment by kchezik** [comment]
I've been able to look at some that failed and they honestly look fine. Maybe I just need to up the control arguments. I'll try that first.

**Comment by seananderson** [comment]
by far the best solution is to see if we can tweak the model settings to get all (or more) converged

**Comment by kchezik** [comment]
You know what we need. We need a function that texts your phone when either your code finishes or quits due to an error and tells you which of the two occurred. That way you could run something and then go have a sandwich and it wouldn't be a waste of time because your code quit and you didn't realize it.

**Comment by seananderson** [comment]
Close: http://cran.r-project.org/web/packages/beepr/index.html

**Comment by kchezik** [comment]
It's clear that beepr has a lot of Mario and War Craft III sounds. Which means Rasmus Baath is about my age because I played a lot of both.

**Comment by kchezik** [comment]
Ended up going the while() route and for Jan-Max-flow, we get three non-converg. out of 1000. If they're all like that it's been a huge headache for a tiny problem.

**Comment by seananderson** [comment]
The slopes are simply too small. Try multiplying them by 10000 (or anything ballpark in that range).

You may also get better performance by using sqrt(Area) / 10000 or something like that. You want all parameters to be not too far away from a magnitude of 1. You may get non-convergence issues but you may also lose some precision without that. Sorry for not catching that before. Those are the kinds of tricks I was using with Stan.

```R
d <- readRDS("error_Data1.rds")
library(ggplot2)
ggplot(d, aes(sqrt(Area), slope_sim)) + geom_point()

library(nlme)
m <- gls(slope_sim*1e4 ~ 1, weights = varExp(form =~sqrt(Area)/1e4), data = d)
m
```

**Comment by seananderson** [comment]
Transforming the Area predictor like that lets you backtransform to the original units after. Alternatively, `sqrt(Area/1e6)`, which might be easier to explain and I think gets you to the same place, basically.

**Comment by seananderson** [comment]
You may need to scale different responses by different fixed amounts if they are dramatically different in magnitude. (e.g. days of year vs. flow volumes)

You're aiming for no one coefficient to be super tiny or super big. Ballpark 1 (or in reality, say, absolute value of 0.01 to 100) is probably good.

**Comment by seananderson** [comment]
Note the note in `?nlme`

```
Note

The function does not do any scaling internally: the optimization will work best when the response is scaled so its variance is of the order of one.
```

This has bitten many people many times. It's also a fairly common issue with any optimization.
