### ISSUE TITLE
4 Panel Plot with Inset Density Plots?

### ISSUE THREAD

**Issue by kchezik** [kchezik/River-Network-Flow-Trends#9]
Hey Sean,

I've created a function that produces a funnel plot with an inset density plot but unfortunately because I'm using the fig() argument in par(), the mfrow() settings are reverted to c(1,1) rather than c(2,2) before I can plot the other response variable figures and their insets. I've tried using layout but it seems to run into the same problem. I bumped into your post on multi-panel plotting but it doesn't cover this issue so I thought I might toss it your way and see if you've tackled this problem before. We can always force the individual plots together in a final 4 panel plot using Adobe or something but I thought I'd make sure it isn't possible in R before going that route as I'm sure these plots will see revision.

Any ideas?

~Kyle

**Comment by kchezik** [comment]
This can all be found in the Code_02 file.

**Comment by seananderson** [comment]
split.screen would work (you can do anything with it), but it's probably 
not worth the hassle of figuring out the coordinates here.

My favourite quick hack for this is TeachingDemos::subplot(). I'll send 
you an example by email.
